# Generated by Django 4.2.17 on 2026-03-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='post',
            name='youtube_url',
            field=models.CharField(blank=True, default='', help_text='YouTube URL', max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('design', 'Design'), ('development', 'Development'), ('music', 'Music'), ('animation', 'Animation'), ('art', 'Art'), ('singer', 'Singer'), ('writing', 'Writing'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
