# Generated by Django 4.2.17 on 2026-03-15 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_chatrequest'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chatrequest',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='chatrequest',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_requests', to='main.project'),
        ),
        migrations.AlterField(
            model_name='chatrequest',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_requests', to='main.post'),
        ),
    ]
