# Generated by Django 6.0.2 on 2026-04-07 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_chatrequest_id_alter_comment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='budget',
            field=models.CharField(help_text='Example: $500-$1000', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='requirements',
            field=models.TextField(help_text='Project requirements'),
        ),
        migrations.AlterField(
            model_name='project',
            name='timeline',
            field=models.CharField(help_text='Example: 2-4 weeks', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='allow_post_messages',
            field=models.BooleanField(default=True, help_text='Let other users to send you direct messages'),
        ),
    ]
