# Generated by Django 4.2.17 on 2026-04-16 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_project_budget_alter_project_requirements_and_more'),
        ('main', '0011_alter_chatrequest_id_alter_comment_id_and_more'),
    ]

    operations = [
    ]
